// <auto-generated />
using System;
using EFCoreCoffeeShop.CoffeeShop;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreCoffeeShop.Migrations
{
    [DbContext(typeof(CoffeeShopContext))]
    partial class CoffeeShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreCoffeeShop.CoffeeShop.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("Quantity");

                    b.Property<int?>("UserInfoId");

                    b.HasKey("ProductId");

                    b.HasIndex("UserInfoId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Name = "Hot Chocolate",
                            Price = 2.5,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 2,
                            Name = "Coffee",
                            Price = 1.5,
                            Quantity = 10
                        },
                        new
                        {
                            ProductId = 3,
                            Name = "Latte",
                            Price = 3.5,
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("EFCoreCoffeeShop.CoffeeShop.UserInfo", b =>
                {
                    b.Property<int>("UserInfoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserInfoId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("EFCoreCoffeeShop.CoffeeShop.Product", b =>
                {
                    b.HasOne("EFCoreCoffeeShop.CoffeeShop.UserInfo", "User")
                        .WithMany("Product")
                        .HasForeignKey("UserInfoId");
                });
#pragma warning restore 612, 618
        }
    }
}
